module.exports = {
  apps: [
    {
      name: "orvanta-server",
      cwd: "./server",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/orvanta-server-error.log",
      out_file: "/root/.pm2/logs/orvanta-server-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "orvanta-client",
      cwd: "./client",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "800M",
      error_file: "/root/.pm2/logs/orvanta-client-error.log",
      out_file: "/root/.pm2/logs/orvanta-client-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "orvanta-admin",
      cwd: "./admin",
      script: "npm",
      args: "run preview -- --port 4173 --host 0.0.0.0",
      env: {
        NODE_ENV: "production",
        PORT: 4173,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/orvanta-admin-error.log",
      out_file: "/root/.pm2/logs/orvanta-admin-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
  ],
};
